const fs=require('fs');
const path=require('path');
const {house,policy,project,interpret}=require('./flows');
const flows=[house,policy,project,interpret];
const pageLabels={house:'AI 找房',policy:'查政策',project:'楼盘解读',interpret:'政策解读'};
const root=path.resolve(__dirname,'..');
const css=fs.readFileSync(path.join(__dirname,'flow.css'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'flow.js'),'utf8');
const encode=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const allDocs=[];
for(const [flowIndex,flow] of flows.entries()){
 const docs=JSON.parse(fs.readFileSync(path.join(root,'docs',flow.key,'nodes.json'),'utf8').replace(/^\uFEFF/,''));
 for(const doc of docs)doc.content=fs.readFileSync(path.join(root,doc.file),'utf8');
 allDocs.push(...docs);
 const html=`<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${flow.title}流程 · 成都住建房产超市</title><style>${css}</style></head>
<body><header><div class="brand"><span class="mark" aria-hidden="true">⌂</span>成都住建 · 房产超市<small>AI 业务流程</small></div><nav class="top-nav" aria-label="业务流程">${flows.map(item=>`<a href="${item.file}" class="${flow.key===item.key?'current':''}" ${flow.key===item.key?'aria-current="page"':''}>${pageLabels[item.key]}</a>`).join('')}</nav><span class="version">V3.1.0 · 流程评审稿</span></header>
<section class="intro"><div><div class="eyebrow">SERVICE FLOW / ${String(flowIndex+1).padStart(2,'0')}</div><h1>${flow.title}<span class="muted">/</span><span class="subtitle">${flow.subtitle}</span></h1><p>${flow.description}</p></div><div class="intro-right"><div class="stat"><strong>${docs.length.toString().padStart(2,'0')}</strong><span>AI 输出节点</span></div><button class="outline-button" id="doc-index">文档目录 <span aria-hidden="true">↗</span></button></div></section>
<main class="workspace"><aside class="rail"><p class="rail-title">流程导航</p><nav id="phases" aria-label="流程阶段"></nav><div class="rail-note"><strong>阅读方式</strong><p>沿箭头阅读流程。<br>点击节点查看说明，<br>点击 .md 打开文档。</p><p>依据原需求 §${flow.source}<br><a class="source-link" href="docs/需求原文.md" target="_blank" rel="noopener">查看需求原文 ↗</a></p></div></aside>
<section class="flow-area" aria-label="${flow.title}流程图"><div class="toolbar"><div class="legend"><span><i class="dot user"></i>用户</span><span><i class="dot ai"></i>AI 输出</span><span><i class="dot"></i>系统</span><span><i class="dot decision"></i>判断</span></div><div class="zoom-tools"><button id="zoom-out" aria-label="缩小流程图">−</button><output id="zoom-value" aria-label="当前缩放">100%</output><button id="zoom-in" aria-label="放大流程图">+</button><button id="zoom-fit" class="fit">适宽</button><button id="show-detail" class="mobile-detail" aria-label="查看节点说明">说明</button></div></div><div class="viewport" id="viewport"><div class="stage-wrap" id="stage-wrap"><div class="diagram" id="diagram"></div></div></div><div class="footer-info">实线：处理流向 · 虚线：重试 / 返回 &nbsp; | &nbsp; 点击节点查看说明</div></section>
<aside class="inspector" id="inspector" aria-label="节点详情"><div class="inspector-top"><span><i class="live-dot"></i>节点说明</span><span>NODE DETAILS <button class="inspector-close" id="close-detail" aria-label="关闭节点说明">×</button></span></div><div id="detail" aria-live="polite"></div></aside></main>
<dialog class="modal" id="document-modal" aria-labelledby="modal-title"><div class="modal-bar"><span class="modal-title" id="modal-title"></span><div class="modal-actions"><a id="modal-raw" href="#" target="_blank" rel="noopener">原文件 ↗</a><a id="modal-download" href="#" download>下载 .md ↓</a><button id="modal-close" aria-label="关闭文档">关闭 ×</button></div></div><div id="modal-body"></div></dialog><noscript><p class="no-js">请启用 JavaScript 查看交互流程图，或阅读 <a href="docs/README.md">Markdown 文档索引</a>。</p></noscript>
<script>const FLOW=${encode(flow)};const DOCS=${encode(docs)};\n${js}</script></body></html>`;
 fs.writeFileSync(path.join(root,flow.file),html);
 console.log(flow.file+' | '+flow.nodes.length+' nodes | '+docs.length+' AI documents');
}
const overview=`# 成都住建房产超市 AI 流程说明\n\n依据《成都住建房产超市 IM、AI 需求文档》V3.1.0 第 2.4 节整理。\n\n## 使用方式\n\n- 打开 [AI 找房流程](../AI找房流程.html) 或 [AI 政策流程](../AI政策流程.html)。\n- 每个紫色 AI 节点都提供真实 Markdown 文件入口；点击节点可在右侧查看输入、输出与约束，并在页面内阅读全文。\n- 两个 HTML 已内嵌样式、流程数据和节点文档预览，无网络依赖。直接双击即可使用。原文件链接需保留 docs 文件夹与 HTML 的相对位置。\n- 文件是产品流程与输出规格说明，不连接真实 AI、楼盘库或政策库。\n\n## 职责边界\n\nAI：理解意图、提取或转换条件、补问、说明真实查询结果、基于原文解读、生成候选问题。\n\n系统：字段和条件校验、真实业务查询、排序与限制数量、政策时效计算、验证候选问题、构造业务卡片与真实页面路径、会话状态保存、异常与重试。\n\n业务数据异常不等于零结果。任何候选推荐问题需经过真实数据校验后才能展示。每次楼盘 / 政策最多 5 条，推荐问题最多 3 个。普通回复建议 50–150 字。\n\n## 建议契约与待确认口径\n\n以下为流程细化建议，原需求未提供完整接口协议；节点文档中的字段名和 JSON 是建议输出契约，研发接入时应与真实接口对齐。\n\n- 最小查询范围：由业务支持字段与查询规则配置。不将区域、预算等全部设为必填；明确楼盘名可查询，“帮我找房”需补问。\n- 预算：“以内”与“以上”分别保留上限与下限；“左右”浮动范围未定义，应按显式配置或追问，不擅自定义；仅报数字时保留解释依据。\n- 非标准需求：需要系统能力与真实数据支持。没有地图和点位，不生成虚假通勤结论。\n- 当前与最新：当前仅用有效政策；最新按业务配置的发布时间或生效时间排序，必须同时标明时效状态。时间缺失应标为待核验。\n- 政策解读：原文同时提出“可简单总结”和“不回答具体政策结论”，此流程按保守口径处理：仅忠实归纳已取得的正文，不补造补贴标准、条件，不作个体资格承诺。缺正文使用受限说明并提供真实详情入口。\n- 普通结果的推荐问题也进行数据验证，延续需求整体准确性原则；不得静默修改原始硬性条件。\n- 查询验证全部失败或无结果时，不生成凑数问题，保留手动输入入口。\n- 页面 / 顾问跳转路径根据可信业务 ID 由系统映射；AI 仅引用已提供的 ID。\n- 本轮仅覆盖新房及购房支持政策；管理端二手房引导配置不意味着本轮扩展二手房流程。\n\n## AI 找房节点\n\n${allDocs.filter(d=>d.id.startsWith('H')).map(d=>`- [${d.id} ${d.title}](${d.file.replace(/^docs\//,'')})`).join('\n')}\n\n## AI 政策节点\n\n${allDocs.filter(d=>d.id.startsWith('P')).map(d=>`- [${d.id} ${d.title}](${d.file.replace(/^docs\//,'')})`).join('\n')}\n\n## 共用状态\n\n发送问题后显示 AI 回复中状态；成功后替换结果。AI 异常、楼盘接口异常、政策接口异常分别提示，重试失败节点并保留条件。进入楼盘详情、政策详情或其他业务页面，保存历史问题、回答、卡片、推荐问题、当前条件与滚动位置；1 天内返回恢复对话。\n\n流程图中的“下一轮”携带上下文回到意图识别；业务不变时进入条件提取，仅覆盖本轮明确修改的条件。任一 AI 节点异常进入公共异常分支；可选追问 H07 / P07 生成失败时，隐藏推荐问题但保留已成功的说明和结果。\n\n[需求原文](需求原文.md)\n`;
const extraIndex=[project,interpret].map(flow=>`## ${flow.title}节点\n\n${allDocs.filter(d=>d.file.startsWith('docs/'+flow.key+'/')).map(d=>`- [${d.id} ${d.title}](${d.file.replace(/^docs\//,'')})`).join('\n')}`).join('\n\n');
const guidance=house.nodes.find(n=>n.fixedReply).description;
const expandedOverview=overview.replace('两个 HTML','四个 HTML').replace('- 打开 [AI 找房流程](../AI找房流程.html) 或 [AI 政策流程](../AI政策流程.html)。',flows.map(flow=>`- [${pageLabels[flow.key]}流程](../${flow.file})`).join('\n'))+`\n## 未识别意图时的系统固定引导\n\n结合有效上下文仍未识别到意图时，系统原样返回以下文案，不调用 AI 生成或改写：\n\n> ${guidance}\n\n保留会话，等待用户继续提问；本轮不进入业务查询。AI 服务异常与未识别意图分别处理。\n\n## 新增独立解读流程\n\n- 楼盘解读对应 PROJECT_QUERY，先确认具体项目，再解释实时业务字段。对象不明确需确认，资料不足使用受限说明。\n- 政策解读对应 POLICY_INTERPRET，先确认政策与版本，再核验原文及有效期。无完整正文使用系统固定受限说明，不补写条件和金额。\n- 既有查政策流程保留查询结果的概要说明与简短解读环节；新政策解读页展示从指定政策到原文校验、引用核验的完整独立过程。\n- 四类意图遵循 [共用意图识别 Prompt](house/H01-intent.md)。跨业务路由承接上下文，进入对应流程的对象 / 条件提取；直接提问时从该流程意图识别开始。\n- 新增对象消歧、引用逐项核验、推荐验证及失败降级为基于原规则的细化建议，尚未连接真实业务接口。\n\n${extraIndex}\n`;
fs.writeFileSync(path.join(root,'docs','README.md'),expandedOverview);
fs.writeFileSync(path.join(root,'README.md'),`# 成都住建房产超市 · AI 业务流程\n\n${flows.map(flow=>`- [${pageLabels[flow.key]}流程](${flow.file})`).join('\n')}\n- [Markdown 文档索引](docs/README.md)\n\n直接双击 HTML 文件即可查看；请保留 docs 文件夹，以便打开和下载 Markdown 文件。四页内置全部必要样式与各自文档预览，无需网络。\n\n修改 src/flows.js、src/detail-flows.js、src/flow.css、src/flow.js 或 docs 中节点文档后，运行 node src/build.js 重新生成。\n`);
